// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm0AkbAca2AjsMAL72qlkpzW0hqtJRqH4',
    appId: '1:79636832284:web:39f3df5703422d33397fd9',
    messagingSenderId: '79636832284',
    projectId: 'k-chat-19faa',
    authDomain: 'k-chat-19faa.firebaseapp.com',
    storageBucket: 'k-chat-19faa.appspot.com',
    measurementId: 'G-42E7GD2BQT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdWDgXsSmBPcvnMh8gZ70XM4k6YsY8BsQ',
    appId: '1:79636832284:android:2c52ba78bc644050397fd9',
    messagingSenderId: '79636832284',
    projectId: 'k-chat-19faa',
    storageBucket: 'k-chat-19faa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGCxnieIasClC_ZGVri_ziN6TnyiaWbVI',
    appId: '1:79636832284:ios:7c694bc1cbd48b77397fd9',
    messagingSenderId: '79636832284',
    projectId: 'k-chat-19faa',
    storageBucket: 'k-chat-19faa.appspot.com',
    iosClientId: '79636832284-ep4djdth2v2aohrce3btbev5p1tsdk0l.apps.googleusercontent.com',
    iosBundleId: 'com.example.testchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGCxnieIasClC_ZGVri_ziN6TnyiaWbVI',
    appId: '1:79636832284:ios:7c694bc1cbd48b77397fd9',
    messagingSenderId: '79636832284',
    projectId: 'k-chat-19faa',
    storageBucket: 'k-chat-19faa.appspot.com',
    iosClientId: '79636832284-ep4djdth2v2aohrce3btbev5p1tsdk0l.apps.googleusercontent.com',
    iosBundleId: 'com.example.testchat',
  );
}
